version: '3'

services:
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gestotus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gestotus321654}
      POSTGRES_DB: ${POSTGRES_DB:-gestotus}
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-gestotus}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-gestotus321654}
      POSTGRES_DB: ${POSTGRES_DB:-gestotus}
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432
  nginx:
    build:
      context: ../
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

volumes:
  postgres: